# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependant',
            name='still_in_school',
            field=models.BooleanField(default=False),
        ),
    ]
