# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_auto_20160504_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Policy'),
        ),
    ]
