# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_auto_20160715_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='inception_date',
            field=models.DateField(null=True),
        ),
    ]
