# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0037_auto_20160715_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=12),
        ),
    ]
