# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0038_auto_20160718_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_payment_method',
            field=models.CharField(default='Ecocash', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Agent'),
        ),
    ]
