# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0041_auto_20160719_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='insured',
            name='insured_ec_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
