# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0042_insured_insured_ec_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_date', models.DateTimeField(auto_now_add=True)),
                ('renewal_version', models.IntegerField(default=0)),
                ('endorsement_version', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='dependant',
            name='endorsement_version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependant',
            name='policy_version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system.PolicyVersion'),
            preserve_default=False,
        ),
    ]
