# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0043_auto_20161203_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='policy_version',
        ),
        migrations.AddField(
            model_name='policyversion',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.Policy'),
            preserve_default=False,
        ),
    ]
