# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-03 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0044_auto_20161203_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependant',
            old_name='policy_version',
            new_name='renewal_version',
        ),
    ]
