# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0045_auto_20161203_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='endorsement_version',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='renewal_version',
            field=models.IntegerField(blank=True),
        ),
    ]
