# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0046_auto_20161216_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalment',
            name='endorsement_version',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instalment',
            name='renewal_version',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
