# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-26 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0047_auto_20161219_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='narration',
            field=models.CharField(default='new', max_length=100),
            preserve_default=False,
        ),
    ]
