# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0048_policyversion_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='endorsement_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='renewal_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instalment',
            name='endorsement_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instalment',
            name='renewal_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
