# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-24 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0050_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Instalment')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Payment')),
            ],
        ),
    ]
