# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-24 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0051_allocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_matched',
            new_name='allocated',
        ),
    ]
