# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-24 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0052_auto_20180224_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='matched',
            field=models.BooleanField(default=False),
        ),
    ]
