# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0053_payment_matched'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FieldManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=100)),
                ('branch_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.BranchManager')),
            ],
        ),
        migrations.AddField(
            model_name='policyversion',
            name='effective_date',
            field=models.DateField(null=True),
        ),
    ]
