# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0054_auto_20180228_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='policy',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='cancelled_date',
            field=models.DateField(null=True),
        ),
    ]
