# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0054_auto_20180228_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyversion',
            name='effective_date',
            field=models.DateField(),
        ),
    ]
