# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0055_auto_20180228_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='cancelled_date',
            field=models.DateField(null=True),
        ),
    ]
