# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0057_policy_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyversion',
            name='effective_date',
            field=models.DateField(null=True),
        ),
    ]
